import * as R from "runtypes";

export const Artwork = R.Record({
  artist: R.Null.Or(
    R.Record({
      _id: R.String,
      id: R.String,
      sortable_id: R.String,
      name: R.String,
      years: R.String,
      public: R.Boolean,
      birthday: R.Null.Or(R.String),
      consignable: R.Boolean,
      deathday: R.Null.Or(R.String),
      nationality: R.String,
      published_artworks_count: R.Number,
      forsale_artworks_count: R.Number,
      artworks_count: R.Number,
      original_width: R.Number.Or(R.Null),
      original_height: R.Number.Or(R.Null),
      image_url: R.Null.Or(R.String),
      image_versions: R.Array(R.String),
      image_urls: R.Record({
        four_thirds: R.String.Or(R.Undefined),
        large: R.String.Or(R.Undefined),
        square: R.String.Or(R.Undefined),
        tall: R.String.Or(R.Undefined),
      }),
      target_supply: R.Boolean,
    })
  ),
  partner: R.Record({
    partner_categories: R.Array(
      R.Record({
        _id: R.String,
        id: R.String,
        category_type: R.String,
        name: R.String,
        internal: R.Boolean,
      })
    ),
    _id: R.String,
    id: R.String,
    default_profile_id: R.Null.Or(R.String),
    default_profile_public: R.Null.Or(R.Boolean),
    sortable_id: R.String,
    type: R.String,
    name: R.String,
    short_name: R.Null.Or(R.String),
    pre_qualify: R.Boolean,
    website: R.String,
    has_full_profile: R.Boolean,
    has_fair_partnership: R.Boolean,
    has_limited_fair_partnership: R.Boolean,
    profile_layout: R.String,
    display_works_section: R.Boolean,
    profile_banner_display: R.Null.Or(R.String),
    profile_artists_layout: R.Null.Or(R.String),
    display_artists_section: R.Boolean,
  }),
  images: R.Array(
    R.Record({
      id: R.String,
      position: R.Number,
      aspect_ratio: R.Number.Or(R.Null),
      downloadable: R.Boolean,
      original_width: R.Number.Or(R.Null),
      original_height: R.Number.Or(R.Null),
      is_default: R.Boolean,
      image_url: R.String.Or(R.Null),
      image_versions: R.Array(R.String),
      image_urls: R.Record({
        large: R.String.Or(R.Undefined),
        large_rectangle: R.String.Or(R.Undefined),
        larger: R.String.Or(R.Undefined),
        medium: R.String.Or(R.Undefined),
        medium_rectangle: R.String.Or(R.Undefined),
        normalized: R.String.Or(R.Undefined),
        small: R.String.Or(R.Undefined),
        square: R.String.Or(R.Undefined),
        tall: R.String.Or(R.Undefined),
      }),
      tile_size: R.Number.Or(R.Null),
      tile_overlap: R.Number.Or(R.Null),
      tile_format: R.String.Or(R.Null),
      tile_base_url: R.String.Or(R.Null),
      max_tiled_height: R.Number.Or(R.Null),
      max_tiled_width: R.Number.Or(R.Null),
      gemini_token: R.String.Or(R.Null),
      gemini_token_updated_at: R.String.Or(R.Null),
    })
  ),
  edition_sets: R.Array(
    R.Record({
      id: R.String,
      size_score: R.Number.Or(R.Null),
      forsale: R.Boolean,
      sold: R.Boolean,
      price: R.String,
      price_cents: R.Array(R.Number).Or(R.Null),
      acquireable: R.Boolean,
      offerable: R.Boolean,
      dimensions: R.Record({
        in: R.String.Or(R.Null),
        cm: R.String.Or(R.Null),
      }),
      editions: R.String,
      display_price_currency: R.String,
      availability: R.String,
    })
  ),
  cultural_makers: R.Array(
    R.Record({
      _id: R.String,
      id: R.String,
      name: R.String,
      full_name: R.String,
      created_at: R.String,
      updated_at: R.String,
    })
  ),
  artists: R.Array(
    R.Record({
      _id: R.String,
      id: R.String,
      sortable_id: R.String,
      name: R.String,
      years: R.String,
      public: R.Boolean,
      birthday: R.String.Or(R.Null),
      consignable: R.Boolean,
      deathday: R.String.Or(R.Null),
      nationality: R.String.Or(R.Null),
      published_artworks_count: R.Number,
      forsale_artworks_count: R.Number,
      artworks_count: R.Number,
      original_width: R.Null.Or(R.Number),
      original_height: R.Null.Or(R.Number),
      image_url: R.String.Or(R.Null),
      image_versions: R.Array(R.String),
      image_urls: R.Record({
        four_thirds: R.String.Or(R.Undefined),
        large: R.String.Or(R.Undefined),
        square: R.String.Or(R.Undefined),
        tall: R.String.Or(R.Undefined),
      }),
      target_supply: R.Boolean,
    })
  ),
  _id: R.String,
  id: R.String,
  title: R.Null.Or(R.String),
  display: R.String,
  manufacturer: R.String.Or(R.Null),
  category: R.String,
  medium: R.String,
  unique: R.Null.Or(R.Boolean),
  forsale: R.Boolean,
  sold: R.Boolean,
  date: R.String,
  dimensions: R.Record({ in: R.Null.Or(R.String), cm: R.Null.Or(R.String) }),
  price: R.String,
  series: R.Null.Or(R.String),
  availability: R.String,
  ecommerce: R.Boolean,
  offer: R.Boolean,
  tags: R.Array(R.String),
  width: R.Null.Or(R.String),
  height: R.Null.Or(R.String),
  depth: R.Null.Or(R.String),
  diameter: R.String.Or(R.Null),
  width_cm: R.Number.Or(R.Null),
  height_cm: R.Number.Or(R.Null),
  depth_cm: R.Number.Or(R.Null),
  diameter_cm: R.Number.Or(R.Null),
  metric: R.Null.Or(R.String),
  size_score: R.Null.Or(R.Number),
  duration: R.String.Or(R.Null),
  website: R.Null.Or(R.String),
  signature: R.String,
  default_image_id: R.Null.Or(R.String),
  provenance: R.String,
  literature: R.String,
  exhibition_history: R.String,
  collecting_institution: R.String,
  additional_information: R.String,
  image_rights: R.String,
  relevant_auction_results: R.String,
  blurb: R.String,
  price_hidden: R.Boolean,
  edition_sets_count: R.Number,
  published: R.Boolean,
  private: R.Boolean,
  feature_eligible: R.Boolean,
  price_currency: R.Null.Or(R.String),
  price_includes_tax: R.Boolean,
  price_cents: R.Array(R.Number).Or(R.Null),
  sale_message: R.Null.Or(R.String),
  inquireable: R.Boolean,
  acquireable: R.Boolean,
  offerable: R.Boolean,
  published_at: R.String,
  can_share: R.Boolean,
  can_share_image: R.Boolean,
  deleted_at: R.Null,
  publisher: R.String.Or(R.Null),
  comparables_count: R.Number,
  cultural_maker: R.String.Or(R.Null),
  sale_ids: R.Array(R.String),
  attribution_class: R.Null.Or(R.String),
  framed: R.Null.Or(R.Boolean),
  certificate_of_authenticity: R.Boolean.Or(R.Null),
  condition_description: R.Null.Or(R.String),
  signed_by_artist: R.Boolean.Or(R.Null),
  stamped_by_artist_estate: R.Boolean.Or(R.Null),
  sticker_label: R.Boolean.Or(R.Null),
  signed_other: R.Boolean.Or(R.Null),
  not_signed: R.Boolean.Or(R.Null),
  pickup_available: R.Boolean.Or(R.Null),
  domestic_shipping_fee_cents: R.Number.Or(R.Null),
  international_shipping_fee_cents: R.Number.Or(R.Null),
  shipping_origin: R.Array(R.String).Or(R.Null),
  eu_shipping_origin: R.Boolean,
  current_version_id: R.Null.Or(R.String),
  unlisted: R.Boolean,
});

export type Artwork = R.Static<typeof Artwork>;
